#!/bin/bash

# WD=`pwd`
# 
# cd ../ssh-cron 
#     build man || exit 1
# cd $WD

yodl2html index.yo || exit 1

#scp ../ssh-cron/tmp/manhtml/ssh-cron.1.html index.html \
#    fbb,ssh-cron@web.sourceforge.net:htdocs/

scp index.html fbb,sshcron@web.sourceforge.net:htdocs/

echo -n "update the images as well [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    scp sshcron.jpg fbb,sshcron@web.sourceforge.net:htdocs/
fi

rm index.html

# cd ../ssh-cron 
#     build distclean



