// Generated by Bisonc++ V4.08.00 on Fri, 09 May 2014 22:42:56 +0200

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {270, 2}, // 1: startrule ->  startrule line
     {270, 0}, // 2: startrule ->  <empty>
     {272, 1}, // 3: plainNoWScolonAssign (NR) ->  NR
     {272, 1}, // 4: plainNoWScolonAssign (ID) ->  ID
     {272, 1}, // 5: plainNoWScolonAssign ('*') ->  '*'
     {272, 1}, // 6: plainNoWScolonAssign ('/') ->  '/'
     {272, 1}, // 7: plainNoWScolonAssign (',') ->  ','
     {272, 1}, // 8: plainNoWScolonAssign ('-') ->  '-'
     {272, 1}, // 9: plainNoWScolonAssign (CHAR) ->  CHAR
     {273, 1}, // 10: noWScolonAssign ->  plainNoWScolonAssign
     {274, 1}, // 11: plainNoWS ->  plainNoWScolonAssign
     {274, 1}, // 12: plainNoWS (':') ->  ':'
     {274, 1}, // 13: plainNoWS ('=') ->  '='
     {275, 1}, // 14: noWStoken ->  plainNoWS
     {276, 1}, // 15: plainToken (WS) ->  WS
     {276, 1}, // 16: plainToken ->  plainNoWS
     {277, 1}, // 17: token ->  plainToken
     {278, 1}, // 18: optTokens ->  tokens
     {278, 0}, // 19: optTokens ->  <empty>
     {279, 2}, // 20: tokens ->  tokens token
     {279, 1}, // 21: tokens ->  token
     {280, 2}, // 22: noWSsequence ->  noWStoken optTokens
     {281, 2}, // 23: noWScolonAssignSequence ->  noWScolonAssign optTokens
     {282, 2}, // 24: optWS (WS) ->  optWS WS
     {282, 0}, // 25: optWS ->  <empty>
     {283, 0}, // 26: nameContents ->  <empty>
     {283, 3}, // 27: nameContents (':') ->  ':' optWS noWSsequence
     {283, 3}, // 28: nameContents ('=') ->  '=' optWS noWSsequence
     {283, 1}, // 29: nameContents ->  noWScolonAssignSequence
     {284, 3}, // 30: nameLine (ID) ->  ID optWS nameContents
     {285, 1}, // 31: nr (NR) ->  NR
     {286, 0}, // 32: optStep ->  <empty>
     {286, 2}, // 33: optStep ('/') ->  '/' nr
     {287, 1}, // 34: addNr ->  nr
     {288, 4}, // 35: numberUnit ('-') ->  nr '-' nr optStep
     {288, 1}, // 36: numberUnit ->  addNr
     {289, 3}, // 37: numberSequence (',') ->  numberSequence ',' numberUnit
     {289, 1}, // 38: numberSequence ->  numberUnit
     {290, 1}, // 39: timeEnds (WS) ->  WS
     {291, 3}, // 40: allSequence ('*') ->  '*' optStep timeEnds
     {292, 1}, // 41: numberSpec ->  allSequence
     {292, 2}, // 42: numberSpec ->  numberSequence timeEnds
     {293, 1}, // 43: timeUnit ->  numberUnit
     {293, 1}, // 44: timeUnit (ID) ->  ID
     {294, 3}, // 45: timeSequence (',') ->  timeSequence ',' timeUnit
     {294, 1}, // 46: timeSequence ->  timeUnit
     {295, 1}, // 47: timeSpec ->  allSequence
     {295, 2}, // 48: timeSpec ->  timeSequence timeEnds
     {296, 1}, // 49: minutes ->  numberSpec
     {297, 1}, // 50: hours ->  numberSpec
     {298, 1}, // 51: dayOfMonth ->  numberSpec
     {299, 1}, // 52: monthOfYear ->  timeSpec
     {300, 1}, // 53: dayOfWeek ->  timeSpec
     {301, 1}, // 54: command ->  noWSsequence
     {302, 6}, // 55: cronLine ->  minutes hours dayOfMonth monthOfYear dayOfWeek command
     {303, 1}, // 56: contents ->  nameLine
     {303, 1}, // 57: contents ->  cronLine
     {303, 1}, // 58: contents (_error_) ->  _error_
     {304, 0}, // 59: preamble ->  <empty>
     {305, 2}, // 60: optContents ->  preamble contents
     {305, 0}, // 61: optContents ->  <empty>
     {271, 2}, // 62: line ('\x0a') ->  optContents '\x0a'
     {306, 1}, // 63: startrule_$ ->  startrule
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },             
    { {     270}, {  1} }, // startrule
    { {       0}, { -2} },             
};

SR__ s_1[] =
{
    { { REQ_DEF}, {            6} },               
    { {     271}, {            2} }, // line       
    { {     305}, {            3} }, // optContents
    { {     304}, {            4} }, // preamble   
    { {   _EOF_}, { PARSE_ACCEPT} },               
    { {      10}, {          -61} }, // '\x0a'     
    { {       0}, {          -59} },               
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },          
    { {        10}, { 5} }, // '\x0a'
    { {         0}, { 0} },          
};

SR__ s_4[] =
{
    { { ERR_REQ}, { 15} },                  
    { {     303}, {  6} }, // contents      
    { {     284}, {  7} }, // nameLine      
    { {     302}, {  8} }, // cronLine      
    { { _error_}, {  9} }, // _error_       
    { {     259}, { 10} }, // ID            
    { {     296}, { 11} }, // minutes       
    { {     292}, { 12} }, // numberSpec    
    { {     291}, { 13} }, // allSequence   
    { {     289}, { 14} }, // numberSequence
    { {      42}, { 15} }, // '*'           
    { {     288}, { 16} }, // numberUnit    
    { {     285}, { 17} }, // nr            
    { {     287}, { 18} }, // addNr         
    { {     258}, { 19} }, // NR            
    { {       0}, {  0} },                  
};

SR__ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   2} },         
    { {     282}, {  20} }, // optWS
    { {       0}, { -25} },         
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, { 10} },                  
    { {       297}, { 21} }, // hours         
    { {       292}, { 22} }, // numberSpec    
    { {       291}, { 13} }, // allSequence   
    { {       289}, { 14} }, // numberSequence
    { {        42}, { 15} }, // '*'           
    { {       288}, { 16} }, // numberUnit    
    { {       285}, { 17} }, // nr            
    { {       287}, { 18} }, // addNr         
    { {       258}, { 19} }, // NR            
    { {         0}, {  0} },                  
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       290}, { 23} }, // timeEnds
    { {        44}, { 24} }, // ','     
    { {       257}, { 25} }, // WS      
    { {         0}, {  0} },            
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   3} },           
    { {     286}, {  26} }, // optStep
    { {      47}, {  27} }, // '/'    
    { {       0}, { -32} },           
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   2} },       
    { {      45}, {  28} }, // '-'
    { {       0}, { -34} },       
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_20[] =
{
    { { REQ_DEF}, {  15} },                           
    { {     283}, {  29} }, // nameContents           
    { {     257}, {  30} }, // WS                     
    { {      58}, {  31} }, // ':'                    
    { {      61}, {  32} }, // '='                    
    { {     281}, {  33} }, // noWScolonAssignSequence
    { {     273}, {  34} }, // noWScolonAssign        
    { {     272}, {  35} }, // plainNoWScolonAssign   
    { {     258}, {  36} }, // NR                     
    { {     259}, {  37} }, // ID                     
    { {      42}, {  38} }, // '*'                    
    { {      47}, {  39} }, // '/'                    
    { {      44}, {  40} }, // ','                    
    { {      45}, {  41} }, // '-'                    
    { {     260}, {  42} }, // CHAR                   
    { {       0}, { -26} },                           
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, { 10} },                  
    { {       298}, { 43} }, // dayOfMonth    
    { {       292}, { 44} }, // numberSpec    
    { {       291}, { 13} }, // allSequence   
    { {       289}, { 14} }, // numberSequence
    { {        42}, { 15} }, // '*'           
    { {       288}, { 16} }, // numberUnit    
    { {       285}, { 17} }, // nr            
    { {       287}, { 18} }, // addNr         
    { {       258}, { 19} }, // NR            
    { {         0}, {  0} },                  
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  5} },              
    { {       288}, { 45} }, // numberUnit
    { {       285}, { 17} }, // nr        
    { {       287}, { 18} }, // addNr     
    { {       258}, { 19} }, // NR        
    { {         0}, {  0} },              
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       290}, { 46} }, // timeEnds
    { {       257}, { 25} }, // WS      
    { {         0}, {  0} },            
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  3} },      
    { {       285}, { 47} }, // nr
    { {       258}, { 19} }, // NR
    { {         0}, {  0} },      
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  3} },      
    { {       285}, { 48} }, // nr
    { {       258}, { 19} }, // NR
    { {         0}, {  0} },      
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   2} },         
    { {     282}, {  49} }, // optWS
    { {       0}, { -25} },         
};

SR__ s_32[] =
{
    { { DEF_RED}, {   2} },         
    { {     282}, {  50} }, // optWS
    { {       0}, { -25} },         
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_34[] =
{
    { { REQ_DEF}, {  17} },                        
    { {     278}, {  51} }, // optTokens           
    { {     279}, {  52} }, // tokens              
    { {     277}, {  53} }, // token               
    { {     276}, {  54} }, // plainToken          
    { {     257}, {  55} }, // WS                  
    { {     274}, {  56} }, // plainNoWS           
    { {     272}, {  57} }, // plainNoWScolonAssign
    { {      58}, {  58} }, // ':'                 
    { {      61}, {  59} }, // '='                 
    { {     258}, {  36} }, // NR                  
    { {     259}, {  37} }, // ID                  
    { {      42}, {  38} }, // '*'                 
    { {      47}, {  39} }, // '/'                 
    { {      44}, {  40} }, // ','                 
    { {      45}, {  41} }, // '-'                 
    { {     260}, {  42} }, // CHAR                
    { {       0}, { -19} },                        
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       299}, { 60} }, // monthOfYear 
    { {       295}, { 61} }, // timeSpec    
    { {       291}, { 62} }, // allSequence 
    { {       294}, { 63} }, // timeSequence
    { {        42}, { 15} }, // '*'         
    { {       293}, { 64} }, // timeUnit    
    { {       288}, { 65} }, // numberUnit  
    { {       259}, { 66} }, // ID          
    { {       285}, { 17} }, // nr          
    { {       287}, { 18} }, // addNr       
    { {       258}, { 19} }, // NR          
    { {         0}, {  0} },                
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   3} },           
    { {     286}, {  67} }, // optStep
    { {      47}, {  27} }, // '/'    
    { {       0}, { -32} },           
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 15} },                        
    { {       280}, { 68} }, // noWSsequence        
    { {       257}, { 30} }, // WS                  
    { {       275}, { 69} }, // noWStoken           
    { {       274}, { 70} }, // plainNoWS           
    { {       272}, { 57} }, // plainNoWScolonAssign
    { {        58}, { 58} }, // ':'                 
    { {        61}, { 59} }, // '='                 
    { {       258}, { 36} }, // NR                  
    { {       259}, { 37} }, // ID                  
    { {        42}, { 38} }, // '*'                 
    { {        47}, { 39} }, // '/'                 
    { {        44}, { 40} }, // ','                 
    { {        45}, { 41} }, // '-'                 
    { {       260}, { 42} }, // CHAR                
    { {         0}, {  0} },                        
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 15} },                        
    { {       280}, { 71} }, // noWSsequence        
    { {       257}, { 30} }, // WS                  
    { {       275}, { 69} }, // noWStoken           
    { {       274}, { 70} }, // plainNoWS           
    { {       272}, { 57} }, // plainNoWScolonAssign
    { {        58}, { 58} }, // ':'                 
    { {        61}, { 59} }, // '='                 
    { {       258}, { 36} }, // NR                  
    { {       259}, { 37} }, // ID                  
    { {        42}, { 38} }, // '*'                 
    { {        47}, { 39} }, // '/'                 
    { {        44}, { 40} }, // ','                 
    { {        45}, { 41} }, // '-'                 
    { {       260}, { 42} }, // CHAR                
    { {         0}, {  0} },                        
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_52[] =
{
    { { REQ_DEF}, {  15} },                        
    { {     277}, {  72} }, // token               
    { {     276}, {  54} }, // plainToken          
    { {     257}, {  55} }, // WS                  
    { {     274}, {  56} }, // plainNoWS           
    { {     272}, {  57} }, // plainNoWScolonAssign
    { {      58}, {  58} }, // ':'                 
    { {      61}, {  59} }, // '='                 
    { {     258}, {  36} }, // NR                  
    { {     259}, {  37} }, // ID                  
    { {      42}, {  38} }, // '*'                 
    { {      47}, {  39} }, // '/'                 
    { {      44}, {  40} }, // ','                 
    { {      45}, {  41} }, // '-'                 
    { {     260}, {  42} }, // CHAR                
    { {       0}, { -18} },                        
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       300}, { 73} }, // dayOfWeek   
    { {       295}, { 74} }, // timeSpec    
    { {       291}, { 62} }, // allSequence 
    { {       294}, { 63} }, // timeSequence
    { {        42}, { 15} }, // '*'         
    { {       293}, { 64} }, // timeUnit    
    { {       288}, { 65} }, // numberUnit  
    { {       259}, { 66} }, // ID          
    { {       285}, { 17} }, // nr          
    { {       287}, { 18} }, // addNr       
    { {       258}, { 19} }, // NR          
    { {         0}, {  0} },                
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       290}, { 75} }, // timeEnds
    { {        44}, { 76} }, // ','     
    { {       257}, { 25} }, // WS      
    { {         0}, {  0} },            
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {  17} },                        
    { {     278}, {  77} }, // optTokens           
    { {     279}, {  52} }, // tokens              
    { {     277}, {  53} }, // token               
    { {     276}, {  54} }, // plainToken          
    { {     257}, {  55} }, // WS                  
    { {     274}, {  56} }, // plainNoWS           
    { {     272}, {  57} }, // plainNoWScolonAssign
    { {      58}, {  58} }, // ':'                 
    { {      61}, {  59} }, // '='                 
    { {     258}, {  36} }, // NR                  
    { {     259}, {  37} }, // ID                  
    { {      42}, {  38} }, // '*'                 
    { {      47}, {  39} }, // '/'                 
    { {      44}, {  40} }, // ','                 
    { {      45}, {  41} }, // '-'                 
    { {     260}, {  42} }, // CHAR                
    { {       0}, { -19} },                        
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 15} },                        
    { {       301}, { 78} }, // command             
    { {       280}, { 79} }, // noWSsequence        
    { {       275}, { 69} }, // noWStoken           
    { {       274}, { 70} }, // plainNoWS           
    { {       272}, { 57} }, // plainNoWScolonAssign
    { {        58}, { 58} }, // ':'                 
    { {        61}, { 59} }, // '='                 
    { {       258}, { 36} }, // NR                  
    { {       259}, { 37} }, // ID                  
    { {        42}, { 38} }, // '*'                 
    { {        47}, { 39} }, // '/'                 
    { {        44}, { 40} }, // ','                 
    { {        45}, { 41} }, // '-'                 
    { {       260}, { 42} }, // CHAR                
    { {         0}, {  0} },                        
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  7} },              
    { {       293}, { 80} }, // timeUnit  
    { {       288}, { 65} }, // numberUnit
    { {       259}, { 66} }, // ID        
    { {       285}, { 17} }, // nr        
    { {       287}, { 18} }, // addNr     
    { {       258}, { 19} }, // NR        
    { {         0}, {  0} },              
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 10:
#line 19 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() = d_scanner.matched();
         }
        break;

        case 14:
#line 34 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() = d_scanner.matched();
         }
        break;

        case 17:
#line 47 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() = d_scanner.matched();
         }
        break;

        case 19:
#line 55 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() = string();
         }
        break;

        case 20:
#line 62 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() += d_scanner.matched();
         }
        break;

        case 21:
#line 67 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() = d_scanner.matched();
         }
        break;

        case 22:
#line 75 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() += d_vsp__[0].data<Tag__::STRING>();
         }
        break;

        case 23:
#line 83 "rules/tokens"
        {
         d_val__.get<Tag__::STRING>() += d_vsp__[0].data<Tag__::STRING>();
         }
        break;

        case 31:
#line 3 "rules/timespec"
        {
         d_val__.get<Tag__::INT>() = stol(d_scanner.matched());
         }
        break;

        case 32:
#line 10 "rules/timespec"
        {
         d_val__.get<Tag__::INT>() = 1;
         }
        break;

        case 33:
#line 15 "rules/timespec"
        {
         d_val__.get<Tag__::INT>() = d_vsp__[0].data<Tag__::INT>();
         }
        break;

        case 34:
#line 22 "rules/timespec"
        {
         d_cronData.addNr(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 35:
#line 29 "rules/timespec"
        {
         d_cronData.addRange(d_vsp__[-3].data<Tag__::INT>(), d_vsp__[-1].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 39:
#line 44 "rules/timespec"
        {
         emsg.on();
         }
        break;

        case 40:
#line 51 "rules/timespec"
        {
         d_cronData.setAll(d_vsp__[-1].data<Tag__::INT>());
         }
        break;

        case 44:
#line 67 "rules/timespec"
        {
         d_cronData.addName(d_scanner.matched());
         }
        break;

        case 49:
#line 3 "rules/cronline"
        {
         d_cronData.setMinutes();
         }
        break;

        case 50:
#line 10 "rules/cronline"
        {
         d_cronData.setHours();
         }
        break;

        case 51:
#line 17 "rules/cronline"
        {
         d_cronData.setDayOfMonth();
         }
        break;

        case 52:
#line 24 "rules/cronline"
        {
         d_cronData.setMonthOfYear();
         }
        break;

        case 53:
#line 31 "rules/cronline"
        {
         d_cronData.setDayOfWeek();
         d_scanner.getTail();
         }
        break;

        case 54:
#line 39 "rules/cronline"
        {
         d_cronData.setCommand(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 55:
#line 46 "rules/cronline"
        {
         d_cronData.process();
         }
        break;

        case 59:
#line 10 "rules/line"
        {
         d_cronData.reset(d_scanner.lineNr());
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



